<?php  if($this->images['list']):?>
	<?php if (!$this->showTr):?>
	<table class="table table-striped table-bordered" id="tableList">
		<thead>
			<th>ID</th>
			<th>名称</th>
			<th>类型</th>
			<th>node_id</th>
			<th>block_id</th>
			<th>trunk_id</th>
			<th>宽</th>
			<th>高</th>
			<th class="text-right">大小</th>
			<th>创建时间</th>
		</thead>
		<tbody>
	<?php endif?>

	<?php foreach($this->images['list'] as $image):
		$imgName = $image['id'].'.'.$image['img_ext'];
		$rimgId = bin2hex($image['rimg_id']);
	?>
	<tr>
		<td><?=$image['incr_id']?></td>
		<td><a href="<?=$image['img_url']?>" target="_blank" data-uk-lightbox="{group:'my-group'}" title="<?=$imgName?>"><?=$imgName?></a></td>
		<td>
			<?php if($rimgId == 0):?>
			<span class="text-muted">普通</span>
			<?php else:?>
			<span class="text-danger">参考</span>
			<?php endif?>
		</td>
		<td><?=$image['node_id']?></td>
		<td><?=$image['block_id']?></td>
		<td><?=$image['file_id']?></td>
		<td><?=$image['img_width']?></td>
		<td><?=$image['img_height']?></td>
		<td class="text-right"><?=sprintf('%.2fK', $image['img_length']/1024)?></td>
		<td><?=date('Y/m/d H:i:s', $image['create_time'])?></td>
	</tr>
	<?php endforeach?>
	
	<?php if (!$this->showTr):?>
	</tbody>
	</table>
	
	<?php if($this->np_url):?>
		<a href="<?=$this->np_url?>" id="linkNextPage">下一页</a>
		<?php endif?>
		
		<script>
			var tbody = $('#tableList tbody');
			$('#linkNextPage').click(function(){
				var self = this;
				$.get(this.href, function(ret){
					if (ret.err != 'hapn.ok') {
						return;
					}
					var data = ret.data;
					tbody.append(data.html);
					if (data.np_url) {
						self.href = data.np_url;
					} else {
						self.style.display = 'none';
					}
				});
				return false;
			});
		</script>
	<?php endif?>

<?php elseif (!$this->showTr):?>
<p>还没有任何图片</p>
<?php endif?>
