<?php $this->setLayout('_private/tpl/layout.phtml')?>
<h1>添加节点</h1>

<form method="post" action="/guanli/node/_add">
    <input type="text" class="form-control" name="data[node_id]" placeholder="节点ID...">
    <br/>
    <input type="text" class="form-control" name="data[node_name]" placeholder="节点名称...">
    <br/>
    <input type="text" class="form-control" name="data[node_url]" placeholder="节点网址...">
    <br/>
    <input type="text" class="form-control" name="data[image_url]" placeholder="图片网址...">
    <br/>
    <input type="text" class="form-control" name="data[node_db]" placeholder="数据库地址...">
    <br/>
    <input type="text" class="form-control" name="data[image_dir]" placeholder="图片根目录...">
    <br/>
    <button class="btn btn-primary btn-lg" type="submit">添加</button>
    <a href="/guanli/node/">返回</a>
</form>
