<!doctype html>
<html lang="en">
<head>
	<meta charset="UTF-8" />
	<title><?=$this->title?></title>
	<link rel="stylesheet" href="/css/bootstrap.min.css"/>
	<link rel="stylesheet" href="/css/bootstrap-theme.min.css"/>
	<script src="/js/jquery.js"></script>
	<script src="/js/bootstrap.min.js"></script>
</head>
<body>
	<div class="container">
	
	<?php if (!$this->notShowNav):?>
	<nav class="navbar navbar-default">
		<div class="container-fluid">
			<div class="collapse navbar-collapse">
				<ul class="nav navbar-nav">
					<li ><a href="/guanli/node/">首页</a></li>
					<li ><a href="/image/upload/">上传</a></li>
				</ul>
			</div>
		</div>
	</nav>
	<?php endif?>
	<?=$this->getBlock('__BODY__')?>
	
	<footer>
		<p class="text-center">
			<em>copyright &copy; jiehun.com.cn</em>
		</p>
	</footer>
	</div>
</body>
</html>