<!DOCTYPE html>
<html>
<head>
<title>You're not authorized to access this page (401)</title>
<link href="/static/css/normalize.css" media="screen" rel="stylesheet"
	type="text/css" />
<link href="/static/css/bootstrap.min.css" media="screen"
	rel="stylesheet" type="text/css" />
</head>

<body>
	<div class="container text-center">
		<h1>401 Unauthorized</h1>
		<h3>你没有查看该页面的权限！</h3>
		<hr />

		<a href="/" class="glyphicon glyphicon-home">返回首页</a> <a href=""
			class="glyphicon glyphicon-refresh">刷新</a>
	</div>
</body>
</html>
