<!DOCTYPE html>
<html>
<head>
<title>The page you were looking for doesn't exist (404)</title>
<link href="/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
</head>

<body>
	<div class="container text-center">
		<h1>404 Not Found</h1>
		<h3>你所查找的页面不存在，或者已经被删除！</h3>
		<hr />

		<a href="/" class="glyphicon glyphicon-home">返回首页</a> <a href=""
			class="glyphicon glyphicon-refresh">刷新</a>
	</div>
</body>
</html>
